"""
Django settings for dbmireg project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from os.path import normpath, join, dirname, abspath
from django.utils.crypto import get_random_string
from django.contrib.messages import constants as message_constants
import sys
from dbmireg import environment

chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environment.ENV_STR("SECRET_KEY", get_random_string(50, chars))
EMAIL_CONFIRM_SALT = environment.ENV_STR("SALT", get_random_string(50, chars))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environment.ENV_BOOL("DJANGO_DEBUG", False)

ALLOWED_HOSTS = environment.ENV_LIST("ALLOWED_HOSTS")

# Set the message level
MESSAGE_LEVEL = message_constants.INFO if not DEBUG else message_constants.DEBUG

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'registration',
    'rest_framework',
    'health_check',
    'pyauth0jwt',
    'raven.contrib.django.raven_compat',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dbmireg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [normpath(join(BASE_DIR, 'templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dbmireg.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("MYSQL_DATABASE"),
        'USER': environment.ENV_STR("MYSQL_USERNAME"),
        'PASSWORD': environment.ENV_STR("MYSQL_PASSWORD"),
        'HOST': environment.ENV_STR("MYSQL_HOST"),
        'PORT': environment.ENV_STR("MYSQL_PORT"),
    }
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


#########
# STATIC FILE CONFIGS
DJANGO_ROOT = dirname(dirname(abspath(__file__)))
STATIC_ROOT = normpath(join(DJANGO_ROOT, 'assets'))
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    normpath(join(DJANGO_ROOT, 'static')),
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
#########

#########
# Auth0

AUTH0_CLIENT_ID_LIST = environment.ENV_LIST("AUTH0_CLIENT_ID_LIST")
AUTH0_DOMAIN = environment.ENV_STR("AUTH0_DOMAIN")
AUTH0_LOGOUT_URL = environment.ENV_STR("AUTH0_LOGOUT_URL")
AUTHENTICATION_LOGIN_URL = environment.ENV_STR("AUTHENTICATION_LOGIN_URL")

#########

#########
# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'registration.permissions.IsAuthenticated',
        'registration.permissions.IsAssociatedUser'
    ),
    'PAGE_SIZE': 10,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'registration.permissions.DBMIAuthentication',
    ),
}

###

#########
# Application settings
LOGIN_URL = '/login/'

DBMI_AUTHZ_URL = environment.ENV_STR("DBMI_AUTHZ_URL")

COOKIE_DOMAIN = environment.ENV_STR("COOKIE_DOMAIN")

EMAIL_BACKEND = environment.ENV_STR("EMAIL_BACKEND", 'django_smtp_ssl.SSLEmailBackend')
EMAIL_USE_SSL = EMAIL_BACKEND == 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = environment.ENV_STR("EMAIL_HOST")
EMAIL_HOST_USER = environment.ENV_STR("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = environment.ENV_STR("EMAIL_HOST_PASSWORD")
EMAIL_PORT = environment.ENV_STR("EMAIL_PORT")

DEFAULT_FROM_EMAIL = environment.ENV_STR("DEFAULT_FROM_EMAIL", "registration-no-reply@dbmi.hms.harvard.edu")
###

#########
# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '[DBMIReg] - [%(asctime)s][%(levelname)s]'
                      '[%(name)s.%(funcName)s:%(lineno)d] - %(message)s',
        },
    },
    'handlers': {
        'sentry': {
            'level': 'ERROR', # To capture more than ERROR, change to WARNING, INFO, etc.
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
            'tags': {'custom-tag': 'x'},
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'stream': sys.stdout,
        },
    },
    'root': {
        'handlers': ['console', 'sentry'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'raven': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}
###

# Default settings
BOOTSTRAP3 = {

    # The URL to the jQuery JavaScript file
    'jquery_url': '//code.jquery.com/jquery.min.js',

    # The Bootstrap base URL
    'base_url': '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/',

    # The complete URL to the Bootstrap CSS file (None means derive it from base_url)
    'css_url': None,

    # The complete URL to the Bootstrap JavaScript file (None means derive it from base_url)
    'javascript_url': None,

    # Include jQuery with Bootstrap JavaScript (affects django-bootstrap3 template tags)
    'include_jquery': True,
}

RAVEN_URL = environment.ENV_STR("RAVEN_URL")
if RAVEN_URL:
    RAVEN_CONFIG = {
        'dsn': RAVEN_URL,
        # If you are using git, you can also automatically configure the
        # release based on the git info.
        'release': '1',
        'site': 'dbmireg'
    }

#########
