# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161030_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliationType',
        ),
    ]
