# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='registration',
            name='street_address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address 1'),
        ),
        migrations.AddField(
            model_name='registration',
            name='street_address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address 2'),
        ),
        migrations.AddField(
            model_name='registration',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter Handle'),
        ),
        migrations.AddField(
            model_name='registration',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip'),
        ),
    ]
