# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170328_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='registration',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternate Email'),
        ),
        migrations.AddField(
            model_name='registration',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='registration',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Professional Title'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='none', max_length=254, verbose_name='Registration Email'),
            preserve_default=False,
        ),
    ]
