# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180201_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='affiliation_type',
            field=models.CharField(blank=True, choices=[('AC', 'Academic'), ('IN', 'Industry'), ('', 'None')], default='AC', max_length=20, null=True, verbose_name='Affiliation Type'),
        ),
    ]
