# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180202_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='affiliation_type',
            field=models.CharField(blank=True, choices=[('AC', 'Academic'), ('IN', 'Industry'), ('', 'None')], default='', max_length=20, null=True, verbose_name='Affiliation Type'),
        ),
    ]
