# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20180209_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
