# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_registration_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
