# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Registration Email')),
                ('affiliation_type', models.CharField(blank=True, choices=[('AC', 'Academic'), ('IN', 'Industry')], default='AC', max_length=20, null=True, verbose_name='Affiliation Type')),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliation')),
                ('software_interest', models.BooleanField(default=False)),
                ('data_interest', models.BooleanField(default=False)),
                ('technical_consulatation_interest', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
