# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_delete_affiliationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
