# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registration_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='E-Mail Confirmed'),
        ),
    ]
